added another failing dockerfile

diff --git a/Dockerfile.toolchain_test2 b/Dockerfile.toolchain_test2
--- a/Dockerfile.toolchain_test2
+++ b/Dockerfile.toolchain_test2
@@ -22,7 +22,6 @@ RUN apt-get update && apt-get install -y \
     curl \
     g++ \
     python3 \
-    python3-pip \
     python3-setuptools \
     python3-dev \
     clang \
@@ -35,14 +34,15 @@ RUN apt-get update && apt-get install -y \
     libc6 \
     libc6-dev \
     libc6-dbg \
+    ca-certificates \
     --no-install-recommends \
     && ln -s /usr/bin/$(ls /usr/bin | grep perf) /usr/bin/perf \
     && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
 
 # Copy and install the memgraph deb package
-RUN curl https://download.memgraph.com/memgraph/v${MG_VERSION}/ubuntu-24.04/memgraph_${MG_VERSION}-1_amd64.deb --output memgraph.deb \
-&& dpkg -i memgraph.deb \
-&& rm memgraph.deb 
+# RUN curl https://download.memgraph.com/memgraph/v${MG_VERSION}/ubuntu-24.04/memgraph_${MG_VERSION}-1_amd64.deb --output memgraph.deb \
+# && dpkg -i memgraph.deb \
+# && rm memgraph.deb 
 
 
 # Set the memgraph query modules library path (required)
@@ -70,10 +70,23 @@ ENV MG_TOOLCHAIN_ROOT=/opt/toolchain-v7 \
 WORKDIR /mage
 COPY . /mage
 
+# clone memgraph repe (need to do this here for auth_module requirements)
+RUN cd / \
+    && git clone https://github.com/memgraph/memgraph.git \
+    && cd memgraph \
+    && git checkout toolchain-v7 \
+    && pwd \
+    && cd /
+
+# install pip without apt
+RUN curl -O https://bootstrap.pypa.io/get-pip.py
+RUN python3 get-pip.py --break-system-packages
+
+
 # Install Python requirements for both production and testing
-RUN python3 -m pip install -r /mage/python/requirements.txt --break-system-packages \
-    && python3 -m pip install -r /mage/python/tests/requirements.txt --break-system-packages \
-    && python3 -m pip install --no-cache-dir -r /usr/lib/memgraph/auth_module/requirements.txt --break-system-packages
+RUN python3 -m pip install -r /mage/python/requirements.txt --break-system-packages 
+RUN python3 -m pip install -r /mage/python/tests/requirements.txt --break-system-packages 
+RUN python3 -m pip install --no-cache-dir -r /memgraph/src/auth/reference_modules/requirements.txt --break-system-packages
 
 # Install Torch and DGL dependencies (if tests require them)
 RUN python3 -m pip install torch-sparse torch-cluster torch-spline-conv torch-geometric torch-scatter -f https://data.pyg.org/whl/torch-2.3.0+cu121.html --break-system-packages \
@@ -84,16 +97,34 @@ RUN curl https://sh.rustup.rs -sSf | sh -s -- -y \
     && export PATH="/root/.cargo/bin:${PATH}" \
     && python3 /mage/setup build -p /usr/lib/memgraph/query_modules/ --cpp-build-flags CMAKE_BUILD_TYPE=Release
 
+
+
+RUN /memgraph/environment/os/install_deps.sh install TOOLCHAIN_RUN_DEPS
+RUN /memgraph/environment/os/install_deps.sh install MEMGRAPH_BUILD_DEPS
+RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
+RUN apt install -y nodejs
+RUN cd /memgraph && ./init 
+RUN cd /memgraph && cmake -B build -S . -D CMAKE_TOOLCHAIN_FILE=toolchain.cmake 
+RUN cd /memgraph && cmake --build ./build --target memgraph -- -j$(nproc) 
+RUN cd /memgraph/build && make install -j$(nproc) 
+RUN cd / 
+
+RUN cp -r /usr/lib/memgraph/query_modules/* /memgraph/query_modules/
+
+# Create the memgraph user (and group)
+RUN adduser --system --group memgraph
+
+# Then change ownership of /mage
+RUN chown -R memgraph:memgraph /mage
+
 # Run tests in three parts:
-RUN chown -hR memgraph /mage
 USER memgraph
-# RUN /usr/lib/memgraph/memgraph &
 
-# 1. Run C++ tests using ctest
-RUN cd /mage/cpp/build && ctest --output-on-failure
+# # 1. Run C++ tests using ctest
+# RUN cd /mage/cpp/build && ctest --output-on-failure
 
-# 2. Run Python tests using pytest
-RUN cd /mage/python && python3 -m pytest . || true
+# # 2. Run Python tests using pytest
+# RUN cd /mage/python && python3 -m pytest . || true
 
 RUN /usr/lib/memgraph/memgraph & \
     sleep 5 && \
@@ -101,7 +132,7 @@ RUN /usr/lib/memgraph/memgraph & \
     pkill -f /usr/lib/memgraph/memgraph
 
 
-# this does not work, probably because memgraph and the query modules are compiled with different toolchains
+
 # The final command indicates success if all tests pass.
 CMD ["echo", "All tests passed!"]
 
