modify checkout step

diff --git a/.github/workflows/reusable_test.yml b/.github/workflows/reusable_test.yml
--- a/.github/workflows/reusable_test.yml
+++ b/.github/workflows/reusable_test.yml
@@ -72,14 +72,29 @@ jobs:
       - name: Checkout specific branch in submodule
         run: |
           cd cpp/memgraph
-          if [ -z "${{ inputs.memgraph_ref }}" ] || ! git checkout "${{ inputs.memgraph_ref }}"; then
-            # this may happen if we're using a daily build not directly from master
-            echo "Checkout of '${{ inputs.memgraph_ref }}' failed, checking out master instead."
+          # If no ref is provided, just checkout master.
+          if [ -z "${{ inputs.memgraph_ref }}" ]; then
+            echo "No memgraph_ref provided, checking out master."
             git checkout master
+          else
+            # Temporarily disable exit-on-error to capture the failure of checkout.
+            set +e
+            git checkout "${{ inputs.memgraph_ref }}"
+            checkout_status=$?
+            # Re-enable exit-on-error.
+            set -e
+            
+            # If the checkout failed, fallback to master.
+            if [ $checkout_status -ne 0 ]; then
+              echo "Checkout of '${{ inputs.memgraph_ref }}' failed, checking out master instead."
+              git checkout master
+            fi
           fi
+          echo "DEBUG: Last status $?"
           
           # Only pull if we are on a branch.
           current_branch=$(git symbolic-ref --short -q HEAD)
+          echo "Current branch: $current_branch"
           if [ -n "$current_branch" ]; then
             if [[ "${{ inputs.memgraph_ref_update }}" == "true" ]]; then
               git pull
